Looks Very Solid Still
RIT-EVT/LVSS pull request #6
Opened 2024-04-20 15:18 UTC by DiegoLHendrix

2024-04-20 19:26 UTC, mjmagee991 requested changes
A couple things to clean up

2024-04-20 19:26 UTC, mjmagee991 commented on include/dev/ACS71240.hpp
> +    uint32_t readCounts();
Delete this function. You were just using it for debugging

2024-04-20 19:26 UTC, mjmagee991 commented on src/dev/ACS71240.cpp
> +    int32_t current = (((adcCounts - 1970) * 3300) / 180);
Add a comment explaining this equation

2024-04-20 19:26 UTC, mjmagee991 commented on targets/REV3-ACS71240/main.cpp
> +    IO::ADC& adc0 = IO::getADC<IO::Pin::A1>();
```suggestion
    IO::ADC& adc0 = IO::getADC<IO::Pin::PA1>();
```

2024-04-20 19:26 UTC, mjmagee991 commented on targets/REV3-ACS71240/main.cpp
> +        uart.printf("Counts: %d\r\n", acs71240.readCounts());
```suggestion
```

2024-04-22 16:31 UTC, mjmagee991 requested changes

2024-04-22 16:31 UTC, mjmagee991 commented on include/dev/ACS71240.hpp
>        * @return The current
```suggestion
      * @return The current in mA
```

2024-04-22 16:31 UTC, mjmagee991 commented on src/dev/ACS71240.cpp
> +    int32_t current = (((adcCounts - 1970) * 3300) / 180);
The comment should explain where the 3300 and 180 came from

2024-04-22 16:31 UTC, mjmagee991 commented on targets/REV3-ACS71240/main.cpp
> +        uart.printf("ADC0: %dmA\r\n", acs71240.readCurrent());
Add the wait back in because this will be way too fast to read

2024-04-24 20:37 UTC, mjmagee991 approved these changes
Great work!

2024-09-13 14:30 UTC, tmb5932 approved these changes
# This _gas_ frfr

2024-09-13 15:51 UTC, merged